title: HFSM Fonts
description: Monospaced bitmap Unicode fonts for HFSM2 and FFSM2 libraries
url: "http://font.hfsm.dev"
twitter_username: andrew_gresyk
github_username:  andrew-gresyk

theme: jekyll-theme-minimal # https://github.com/pages-themes/minimal / https://pages.github.com/themes/
logo: assets/logos/hfsm-mono-jekyll.png
